package main

import (
	"encoding/json"
	"io/ioutil"
	"log"
	"net/http"

	"model"
)

func main() {
	url := "https://itunes.apple.com/jp/rss/customerreviews/id=340368403/json"
	resp, err := http.Get(url)
	if err != nil {
		log.Fatal(err)
	}
	defer resp.Body.Close()

	body, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		log.Fatal(err)
	}

	data := &model.AutoGenerated{}
	if err := json.Unmarshal(body, &data); err != nil {
		log.Fatal(err)
	}

	log.Println(data)
}
